version: '3.7'

services:

  fifteen-puzzle:
    container_name: fifteen-puzzle
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:80'
    environment:
      - NODE_ENV=production
      